name: Build CheatEngine server for android

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        android-abi: [x86_64, armeabi-v7a, arm64-v8a]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build ceserver
        working-directory: Cheat Engine/ceserver/extension/ndk-build/
        run: ndk-build APP_ABI=${{ matrix.android-abi }} NDK_PROJECT_PATH="."

      - name: Upload ceserver
        uses: actions/upload-artifact@v3.1.2

        with:
          name: libceserver-extension_${{ matrix.android-abi }}.so
          path: Cheat Engine/ceserver/extension/ndk-build/libs/${{ matrix.android-abi }}
